/*
 * role-overlay-etcd-bootstrap.tf -- Phase 0.G.4
 *
 * One-shot: render /etc/nexus-etcd/etcd.conf.yml on the 3 etcd nodes,
 * write /etc/nexus-etcd/endpoints, start nexus-etcd.service in PARALLEL
 * across all 3 (raft requires simultaneous startup for the first
 * `initial-cluster-state: new` bootstrap), wait for leader election,
 * `etcdctl user add root` + `etcdctl auth enable` for HTTP basic-auth RBAC.
 *
 * Why parallel start: raft elects when a quorum (2/3) is reachable. Sequential
 * start would isolate the first node + spin in pre-vote forever. Parallel
 * gives all 3 a chance to discover each other concurrently.
 *
 * Why HTTP basic-auth (not cert-CN RBAC): client-cert-auth=false on etcd
 * keeps TLS for wire encryption only; Patroni's etcd3 client sends
 * username=root + password=<KV> via Authorization header. Simpler RBAC,
 * one less rotation surface. Cert-CN auth is a future hardening if/when
 * the lab grows multi-tenant etcd.
 *
 * Selective ops: var.enable_etcd_bootstrap. Pre-req: TLS overlay rendered
 * tls/{server-cert,server-key,ca}.pem + etcd-root-password on each etcd
 * node.
 */

locals {
  etcd_members = {
    "etcd-1" = { vm_ip = "192.168.70.64", peer_ip = "192.168.10.64", enabled = var.enable_etcd_1 }
    "etcd-2" = { vm_ip = "192.168.70.65", peer_ip = "192.168.10.65", enabled = var.enable_etcd_2 }
    "etcd-3" = { vm_ip = "192.168.70.66", peer_ip = "192.168.10.66", enabled = var.enable_etcd_3 }
  }

  etcd_members_active = {
    for host, m in local.etcd_members : host => m if m.enabled
  }

  # initial-cluster string: peers ride the VMnet10 backplane on :2380.
  etcd_initial_cluster = join(",", [
    for host, m in local.etcd_members_active : "${host}=https://${m.peer_ip}:2380"
  ])

  # client endpoints: service network VMnet11 on :2379 (Patroni dials here).
  # Use BARE hostnames -- dnsmasq's domain is `nexus.local` (not .nexus.lab),
  # but bare hostnames resolve via dnsmasq + cert SANs include bare host
  # form (etcd-1, etcd-2, etcd-3). Caught at 0.G.4 ratification 2026-05-19
  # transient #7. (.nexus.lab is in allowed_domains for cert issuance but
  # dnsmasq doesn't actually serve that domain.)
  etcd_client_endpoints = join(",", [
    for host, m in local.etcd_members_active : "https://${host}:2379"
  ])
}

resource "null_resource" "etcd_bootstrap" {
  count = var.enable_etcd_bootstrap ? 1 : 0

  triggers = {
    tls_ids          = join(",", [for host in keys(local.etcd_members_active) : null_resource.patroni_tls[host].id])
    members          = local.etcd_initial_cluster
    etcd_bootstrap_v = "1" # v1 (0.G.4) = initial 3-member raft + HTTP basic-auth RBAC (root user, password from KV).
  }

  depends_on = [null_resource.patroni_tls]

  provisioner "local-exec" {
    when        = create
    interpreter = ["pwsh", "-NoProfile", "-Command"]
    command     = <<-PWSH
      $sshUser  = '${var.oltp_node_user}'
      $sshOpts  = @('-o','ConnectTimeout=10','-o','BatchMode=yes','-o','StrictHostKeyChecking=no')
      $endpoints = '${local.etcd_client_endpoints}'
      $initCluster = '${local.etcd_initial_cluster}'
      $timeoutMin = ${var.oltp_cluster_timeout_minutes}

      $members = @(
%{for host, m in local.etcd_members_active~}
        @{ Host='${host}'; VmIp='${m.vm_ip}'; PeerIp='${m.peer_ip}' },
%{endfor~}
        $null
      ) | Where-Object { $_ -ne $null }

      Write-Host "[etcd-bootstrap] $($members.Count) members; initial-cluster=$initCluster; client endpoints=$endpoints"

      # ─── Stage 1: render etcd.conf.yml + endpoints + start nexus-etcd in parallel ───
      foreach ($m in $members) {
        $configBody = @"
# Generated by role-overlay-etcd-bootstrap.tf -- Phase 0.G.4
# DO NOT EDIT BY HAND -- terraform overlay re-applies on every apply.
name: $($m.Host)
data-dir: /var/lib/nexus-etcd
listen-peer-urls: https://$($m.PeerIp):2380
listen-client-urls: https://$($m.VmIp):2379,https://$($m.PeerIp):2379,https://127.0.0.1:2379
initial-advertise-peer-urls: https://$($m.PeerIp):2380
advertise-client-urls: https://$($m.VmIp):2379
initial-cluster: $initCluster
initial-cluster-token: nexus-patroni-etcd
initial-cluster-state: new
peer-transport-security:
  cert-file: /etc/nexus-etcd/tls/server-cert.pem
  key-file: /etc/nexus-etcd/tls/server-key.pem
  trusted-ca-file: /etc/nexus-etcd/tls/ca.pem
  client-cert-auth: true
client-transport-security:
  cert-file: /etc/nexus-etcd/tls/server-cert.pem
  key-file: /etc/nexus-etcd/tls/server-key.pem
  trusted-ca-file: /etc/nexus-etcd/tls/ca.pem
  client-cert-auth: false
auto-compaction-mode: periodic
auto-compaction-retention: "1"
quota-backend-bytes: 2147483648
"@
        $configB64 = [Convert]::ToBase64String([System.Text.UTF8Encoding]::new($false).GetBytes(($configBody -replace "`r`n","`n")))

        $stage = @"
set -euo pipefail
echo '$configB64' | base64 -d | sudo tee /etc/nexus-etcd/etcd.conf.yml > /dev/null
sudo chown root:etcd /etc/nexus-etcd/etcd.conf.yml
sudo chmod 0640 /etc/nexus-etcd/etcd.conf.yml

# /etc/nexus-etcd/endpoints used by nexus-etcdctl wrapper for the
# operator's later RBAC + introspection calls.
echo '$endpoints' | sudo tee /etc/nexus-etcd/endpoints > /dev/null
sudo chown root:etcd /etc/nexus-etcd/endpoints
sudo chmod 0644 /etc/nexus-etcd/endpoints

sudo systemctl daemon-reload
sudo systemctl enable nexus-etcd.service
echo CONFIG_OK
"@
        $stageB64 = [Convert]::ToBase64String([System.Text.UTF8Encoding]::new($false).GetBytes($stage))
        $out = (ssh @sshOpts "$sshUser@$($m.VmIp)" "echo '$stageB64' | base64 -d | bash" 2>&1 | Out-String).Trim()
        if ($out -notmatch 'CONFIG_OK') {
          throw "[etcd-bootstrap] $($m.Host): etcd.conf.yml staging failed -- $out"
        }
        Write-Host "[etcd-bootstrap] $($m.Host): config rendered + service enabled"
      }

      # Start all 3 in parallel (raft needs simultaneous start for fresh bootstrap).
      Write-Host "[etcd-bootstrap] starting nexus-etcd.service on all $($members.Count) members in parallel..."
      $members | ForEach-Object -ThrottleLimit 3 -Parallel {
        $m = $_
        $opts = @('-o','ConnectTimeout=10','-o','BatchMode=yes','-o','StrictHostKeyChecking=no')
        ssh @opts "$using:sshUser@$($m.VmIp)" "sudo systemctl start nexus-etcd.service" 2>&1 | Out-Null
      }

      # ─── Stage 2: wait for leader election ─────────────────────────────────
      Write-Host "[etcd-bootstrap] waiting for cluster leader election..."
      $deadline      = (Get-Date).AddMinutes($timeoutMin)
      $leaderId      = $null
      $rbacHostIndex = $null
      while ((Get-Date) -lt $deadline) {
        for ($i = 0; $i -lt $members.Count; $i++) {
          $m = $members[$i]
          $probe = (ssh @sshOpts "$sshUser@$($m.VmIp)" "sudo /usr/local/sbin/nexus-etcdctl endpoint status --write-out=json 2>/dev/null" 2>&1 | Out-String).Trim()
          # etcdctl --write-out=json reports `"leader":<member-id>` (uint64).
          # Non-zero leader id == cluster has a leader. NB: each etcd node's
          # /etc/hosts maps its own bare hostname to 127.0.1.1 (firstboot's
          # resolver-stability entry), so the probe's own-endpoint dial
          # always fails -- but at least 2/3 of the entries report status.
          # Any non-zero leader value in any response means the cluster is
          # quorate. Caught at 0.G.4 ratification 2026-05-19 transient #8.
          if ($probe -match '"leader":\s*([1-9][0-9]*)') {
            $leaderId      = $matches[1]
            $rbacHostIndex = $i
            break
          }
        }
        if ($leaderId) { break }
        Start-Sleep -Seconds 5
      }
      if (-not $leaderId) {
        foreach ($m in $members) {
          $j = (ssh @sshOpts "$sshUser@$($m.VmIp)" "sudo journalctl -u nexus-etcd.service --no-pager -n 30" 2>&1 | Out-String)
          Write-Host "--- journal $($m.Host) ---"
          Write-Host $j
        }
        throw "[etcd-bootstrap] no leader elected within $timeoutMin min"
      }
      Write-Host "[etcd-bootstrap] cluster has elected a leader (member_id=$leaderId; observed from $($members[$rbacHostIndex].Host))"

      # ─── Stage 3: enable RBAC (root user + auth enable) ─────────────────
      # Idempotent: if `auth enable` was already done, the `auth status` probe
      # returns "Authentication Status: true" + we skip.
      # RBAC commands go through the raft cluster anyway -- any healthy
      # member can execute. Use the same node we successfully probed against.
      Write-Host "[etcd-bootstrap] configuring RBAC (root user + auth enable)..."
      $leaderMember = $members[$rbacHostIndex]
      $rbacStage = @'
set -euo pipefail

# Try anonymous auth status (works pre-enable). Post-enable, ALL ops need
# --user; skip silently if already enabled (idempotent re-apply).
STATUS=$(sudo /usr/local/sbin/nexus-etcdctl auth status 2>&1 || true)
if echo "$STATUS" | grep -q "Authentication Status: true"; then
  echo "[etcd-bootstrap rbac] auth already enabled -- no-op"
  exit 0
fi

# /etc/nexus-etcd/ is 0750 root:etcd; nexusadmin can't traverse without
# sudo. `[ ! -s ... ]` would silently report missing because the parent
# dir isn't traversable, not because the file is absent. Mirror the
# feedback_sudo_required_for_consul_etc_traverse.md pattern.
# (Transient #9 at 0.G.4 ratification 2026-05-19.)
if ! sudo test -s /etc/nexus-etcd/etcd-root-password; then
  echo "[etcd-bootstrap rbac] ERROR: /etc/nexus-etcd/etcd-root-password missing (Vault Agent KV render?)" >&2
  exit 1
fi
ROOT_PWD=$(sudo cat /etc/nexus-etcd/etcd-root-password)

# Create the root user (idempotent: user-add fails harmlessly if exists).
echo "$ROOT_PWD" | sudo /usr/local/sbin/nexus-etcdctl user add root --interactive=false 2>&1 || true

# Grant root the built-in root role (idempotent).
sudo /usr/local/sbin/nexus-etcdctl user grant-role root root 2>&1 || true

# Enable RBAC.
sudo /usr/local/sbin/nexus-etcdctl auth enable

echo "[etcd-bootstrap rbac] RBAC enabled; root user created"
'@
      $rbacB64 = [Convert]::ToBase64String([System.Text.UTF8Encoding]::new($false).GetBytes($rbacStage))
      $rbacOut = (ssh @sshOpts "$sshUser@$($leaderMember.VmIp)" "echo '$rbacB64' | base64 -d | bash" 2>&1 | Out-String)
      if ($LASTEXITCODE -ne 0) {
        Write-Host $rbacOut.Trim()
        throw "[etcd-bootstrap] RBAC enable failed (rc=$LASTEXITCODE)"
      }
      Write-Host $rbacOut.Trim()

      # Final verify: authenticated put/get round-trip
      $verifyStage = @'
set -euo pipefail
ROOT_PWD=$(sudo cat /etc/nexus-etcd/etcd-root-password)
sudo /usr/local/sbin/nexus-etcdctl --user root:"$ROOT_PWD" put /nexus/etcd-bootstrap/marker "$(date -u +%FT%TZ)" >/dev/null
VAL=$(sudo /usr/local/sbin/nexus-etcdctl --user root:"$ROOT_PWD" get /nexus/etcd-bootstrap/marker --print-value-only)
if [ -z "$VAL" ]; then
  echo "[etcd-bootstrap verify] ERROR: put-then-get round-trip returned empty" >&2
  exit 1
fi
echo "[etcd-bootstrap verify] put-then-get round-trip OK (value=$VAL)"
'@
      $verifyB64 = [Convert]::ToBase64String([System.Text.UTF8Encoding]::new($false).GetBytes($verifyStage))
      $verifyOut = (ssh @sshOpts "$sshUser@$($leaderMember.VmIp)" "echo '$verifyB64' | base64 -d | bash" 2>&1 | Out-String)
      if ($LASTEXITCODE -ne 0) {
        Write-Host $verifyOut.Trim()
        throw "[etcd-bootstrap] post-RBAC verify failed (rc=$LASTEXITCODE)"
      }
      Write-Host $verifyOut.Trim()

      Write-Host "[etcd-bootstrap] cluster ready: leader=$leader, $($members.Count) members, RBAC enabled."
    PWSH
  }
}
