/*
 * role-overlay-haproxy-config.tf -- Phase 0.G.4
 *
 * Renders /etc/nexus-haproxy/haproxy.cfg on BOTH haproxy-pg-1 + haproxy-pg-2
 * (for_each over the enabled pair), starts nexus-haproxy.service on each,
 * verifies the LB on each routes :5432 to current Patroni leader via the
 * Patroni REST :8008/leader health probe (returns HTTP 200 only on the
 * leader; HTTP 503 on replicas).
 *
 * Routing model:
 *   - Frontend tcp :5432 + mode tcp + default_backend pg_pool
 *   - Backend pg_pool: 3 servers (pg-primary, pg-replica-1, pg-replica-2)
 *     with `option httpchk GET /leader` on port 8008 -- only the current
 *     Patroni leader returns 200; HAProxy marks the other 2 as DOWN.
 *   - Stats UI on :8404 with HTTP basic-auth (KV-seeded password).
 *
 * Both haproxy nodes run IDENTICAL config -- the keepalived overlay
 * (role-overlay-haproxy-keepalived.tf) handles which one currently
 * binds the VIP .60 and serves traffic.
 *
 * Selective ops: var.enable_haproxy_config. Pre-req: TLS overlay rendered
 * tls/{server-cert,server-key,ca}.pem + patroni-rest-password + haproxy-
 * stats-password on both haproxy nodes.
 */

locals {
  haproxy_nodes = {
    "haproxy-pg-1" = { vm_ip = "192.168.70.67", enabled = var.enable_haproxy_pg_1 }
    "haproxy-pg-2" = { vm_ip = "192.168.70.68", enabled = var.enable_haproxy_pg_2 }
  }

  haproxy_nodes_active = {
    for host, m in local.haproxy_nodes : host => m
    if var.enable_haproxy_config && m.enabled
  }
}

resource "null_resource" "haproxy_config" {
  for_each = local.haproxy_nodes_active

  triggers = {
    tls_id               = null_resource.patroni_tls[each.key].id
    patroni_bootstrap_id = length(null_resource.patroni_bootstrap) > 0 ? null_resource.patroni_bootstrap[0].id : "disabled"
    haproxy_config_v     = "2" # v2 (0.G.4) = HA pair: render config on BOTH haproxy-pg-{1,2}. v1 was the abandoned single-HAProxy variant.

    destroy_vm_ip    = each.value.vm_ip
    destroy_ssh_user = var.oltp_node_user
  }

  depends_on = [null_resource.patroni_tls, null_resource.patroni_bootstrap]

  provisioner "local-exec" {
    when        = create
    interpreter = ["pwsh", "-NoProfile", "-Command"]
    command     = <<-PWSH
      $hostName = '${each.key}'
      $ip       = '${each.value.vm_ip}'
      $sshUser  = '${var.oltp_node_user}'
      $sshOpts  = @('-o','ConnectTimeout=10','-o','BatchMode=yes','-o','StrictHostKeyChecking=no')
      $timeout  = ${var.oltp_cluster_timeout_minutes}

      Write-Host "[haproxy-config $hostName] rendering haproxy.cfg on $hostName ($ip)"

      $configBody = @'
# Generated by role-overlay-haproxy-config.tf -- Phase 0.G.4
# DO NOT EDIT BY HAND -- terraform overlay re-applies on every apply.

global
    log         /dev/log local0
    log         /dev/log local1 notice
    chroot      /var/lib/haproxy
    stats       socket /run/nexus-haproxy/admin.sock mode 660 level admin
    stats       timeout 30s
    user        haproxy
    group       haproxy
    daemon
    maxconn     4096
    ssl-default-bind-options ssl-min-ver TLSv1.2 no-tls-tickets
    ssl-default-server-options ssl-min-ver TLSv1.2 no-tls-tickets

defaults
    log         global
    mode        tcp
    option      tcplog
    option      dontlognull
    timeout     connect    5s
    timeout     client     1m
    timeout     server     1m
    timeout     queue      30s
    retries     3

# Stats UI on :8404 (HTTP basic-auth).
frontend stats
    bind *:8404
    mode http
    stats enable
    stats uri /stats
    stats refresh 10s
    stats show-node
    stats show-legends
    stats show-modules
    stats auth nexusops:__HAPROXY_STATS_PASSWORD__

# PostgreSQL write frontend -- routes to current Patroni leader via /leader probe.
frontend pg_write
    bind *:5432
    mode tcp
    option tcplog
    default_backend pg_pool

backend pg_pool
    mode tcp
    option httpchk GET /leader
    # Patroni REST returns 200 only on the leader; 503 on replicas/paused.
    http-check expect status 200
    # `check` MUST appear on default-server (or each server line) to enable
    # the httpchk probe. Without it, HAProxy CSV shows status="no check" on
    # all 3 backends; backend stays perpetually UP without any failover
    # behavior. (Transient #16 at 0.G.4 ratification 2026-05-19.)
    # `check-ssl` does the TLS handshake against :8008 over HTTPS using the
    # patroni-server CA bundle for verify.
    default-server check inter 2s fall 3 rise 2 on-marked-down shutdown-sessions check-ssl verify required ca-file /etc/nexus-haproxy/tls/ca.pem
    server pg-primary   192.168.70.61:5432 port 8008
    server pg-replica-1 192.168.70.62:5432 port 8008
    server pg-replica-2 192.168.70.63:5432 port 8008
'@

      $configB64 = [Convert]::ToBase64String([System.Text.UTF8Encoding]::new($false).GetBytes(($configBody -replace "`r`n","`n")))

      $stage = @"
set -euo pipefail
# /etc/nexus-haproxy is 0750 root:haproxy -- nexusadmin can't traverse
# without sudo. Same class as transient #9 (etcd-bootstrap).
if ! sudo test -s /etc/nexus-haproxy/haproxy-stats-password; then
  echo '[haproxy-config] ERROR: /etc/nexus-haproxy/haproxy-stats-password missing (Vault Agent KV render?)' >&2
  exit 1
fi
STATS_PWD=`$(sudo cat /etc/nexus-haproxy/haproxy-stats-password)
TMP=`$(mktemp)
echo '$configB64' | base64 -d > "`$TMP"
sed -i "s/__HAPROXY_STATS_PASSWORD__/`$STATS_PWD/" "`$TMP"
# HAProxy 3 requires LF on last line; PS here-string strips trailing LF
# before closing '@. Ensure-newline via `sed -i -e '$a\\'`.
# (Transient #14 at 0.G.4 ratification 2026-05-19, mirrors 0.G.3 #10.)
sed -i -e '`$a\' "`$TMP"
sudo install -m 0640 -o root -g haproxy "`$TMP" /etc/nexus-haproxy/haproxy.cfg
rm -f "`$TMP"

sudo mkdir -p /var/lib/haproxy
sudo chown haproxy:haproxy /var/lib/haproxy
sudo chmod 0755 /var/lib/haproxy

sudo /usr/sbin/haproxy -c -f /etc/nexus-haproxy/haproxy.cfg

sudo systemctl daemon-reload
sudo systemctl enable nexus-haproxy.service
sudo systemctl restart nexus-haproxy.service
echo CONFIG_OK
"@
      $stageB64 = [Convert]::ToBase64String([System.Text.UTF8Encoding]::new($false).GetBytes($stage))
      $stageOut = (ssh @sshOpts "$sshUser@$ip" "echo '$stageB64' | base64 -d | bash" 2>&1 | Out-String)
      if ($stageOut -notmatch 'CONFIG_OK') {
        Write-Host $stageOut.Trim()
        throw "[haproxy-config $hostName] cfg staging + service start failed"
      }
      Write-Host $stageOut.Trim()

      # Wait for HAProxy to mark at least one pg_pool backend UP.
      Write-Host "[haproxy-config $hostName] waiting for HAProxy to mark a Patroni leader UP..."
      $deadline = (Get-Date).AddMinutes($timeout)
      $upHost = $null
      while ((Get-Date) -lt $deadline) {
        $sstate = (ssh @sshOpts "$sshUser@$ip" "echo 'show servers state pg_pool' | sudo socat - UNIX-CONNECT:/run/nexus-haproxy/admin.sock 2>/dev/null" 2>&1 | Out-String)
        # srv_op_state: 0=DOWN, 1=GOING_UP, 2=UP, 3=GOING_DOWN -- field index 5 (0-based after header).
        $upLine = ($sstate -split "`n" | Where-Object { $_ -match '^\d+ pg_pool \d+ pg-' -and ($_ -split '\s+')[5] -eq '2' }) | Select-Object -First 1
        if ($upLine) {
          $upHost = ($upLine -split '\s+')[3]
          break
        }
        Start-Sleep -Seconds 3
      }
      if (-not $upHost) {
        $journal = (ssh @sshOpts "$sshUser@$ip" "sudo journalctl -u nexus-haproxy.service --no-pager -n 30" 2>&1 | Out-String)
        Write-Host $journal
        throw "[haproxy-config $hostName] no pg-* backend marked UP within $timeout min"
      }
      Write-Host "[haproxy-config $hostName] HAProxy marked $upHost UP in pg_pool (current Patroni leader)"

      # Verify stats UI auth gate.
      $authStage = @'
set -euo pipefail
STATS_PWD=$(sudo cat /etc/nexus-haproxy/haproxy-stats-password)
CSV=$(curl -sS --max-time 5 -u "nexusops:$STATS_PWD" "http://127.0.0.1:8404/stats;csv")
if ! echo "$CSV" | grep -q "pg_pool"; then
  echo "[haproxy-config verify] ERROR: stats csv missing pg_pool" >&2
  exit 1
fi
UP_COUNT=$(echo "$CSV" | awk -F',' '$1=="pg_pool" && $2!="BACKEND" && $2!="FRONTEND" && $18=="UP"{c++} END{print c+0}')
if [ "$UP_COUNT" -lt 1 ]; then
  echo "[haproxy-config verify] ERROR: 0 pg_pool members marked UP in stats csv" >&2
  echo "$CSV" | head -20 >&2
  exit 1
fi
echo "[haproxy-config verify] $UP_COUNT pg_pool member(s) UP"
'@
      $authB64 = [Convert]::ToBase64String([System.Text.UTF8Encoding]::new($false).GetBytes($authStage))
      $authOut = (ssh @sshOpts "$sshUser@$ip" "echo '$authB64' | base64 -d | bash" 2>&1 | Out-String)
      if ($LASTEXITCODE -ne 0) {
        Write-Host $authOut.Trim()
        throw "[haproxy-config $hostName] verify failed (rc=$LASTEXITCODE)"
      }
      Write-Host $authOut.Trim()

      Write-Host "[haproxy-config $hostName] ready: :5432 routes to current Patroni leader; :8404 stats UI live."
    PWSH
  }

  provisioner "local-exec" {
    when        = destroy
    interpreter = ["pwsh", "-NoProfile", "-Command"]
    command     = <<-PWSH
      $hostName = '${each.key}'
      $vmIp     = '${self.triggers.destroy_vm_ip}'
      $sshUser  = '${self.triggers.destroy_ssh_user}'
      $sshOpts  = @('-o','ConnectTimeout=5','-o','BatchMode=yes','-o','StrictHostKeyChecking=no')
      Write-Host "[haproxy-config destroy] $${hostName}: stopping nexus-haproxy.service + removing haproxy.cfg"
      ssh @sshOpts "$sshUser@$vmIp" "sudo systemctl disable --now nexus-haproxy.service 2>/dev/null; sudo rm -f /etc/nexus-haproxy/haproxy.cfg" 2>$null
      exit 0
    PWSH
  }
}
