/*
 * role-overlay-patroni-bootstrap.tf -- Phase 0.G.4
 *
 * One-shot: render /etc/nexus-patroni/patroni.yml on the 3 Patroni nodes
 * (per-host name + listen + connect_address), start nexus-patroni.service
 * in PARALLEL, wait for one PRIMARY + 2 SECONDARY (Streaming Replica) +
 * `psql` round-trip via the leader.
 *
 * Why parallel start: Patroni nodes race for the etcd /service/<scope>/leader
 * lease; the first to claim wins + initdb's a fresh datadir + becomes leader.
 * The other 2 see the leader lease + pg_basebackup from it. Sequential start
 * would mean node 1 initdb's + becomes leader; nodes 2/3 start later + each
 * pg_basebackup independently -- same outcome but slower.
 *
 * Why initdb only on the leader: the first node to grab the lease finds an
 * empty data_dir + runs initdb. Subsequent nodes see they're not the leader +
 * pg_basebackup from the leader (Patroni's `replicate` flow).
 *
 * Selective ops: var.enable_patroni_bootstrap. Pre-req: etcd is up + RBAC
 * enabled; TLS rendered on the 3 PG nodes; KV creds rendered (etcd-root,
 * patroni-rest, postgres-superuser, postgres-replication).
 */

locals {
  patroni_nodes = {
    "pg-primary"   = { vm_ip = "192.168.70.61", peer_ip = "192.168.10.61", enabled = var.enable_pg_primary }
    "pg-replica-1" = { vm_ip = "192.168.70.62", peer_ip = "192.168.10.62", enabled = var.enable_pg_replica_1 }
    "pg-replica-2" = { vm_ip = "192.168.70.63", peer_ip = "192.168.10.63", enabled = var.enable_pg_replica_2 }
  }

  patroni_nodes_active = {
    for host, m in local.patroni_nodes : host => m if m.enabled
  }

  # Use BARE hostnames -- dnsmasq's domain is nexus.local, but bare hostnames
  # work via dnsmasq + cert SANs include bare hostname form. See
  # role-overlay-etcd-bootstrap.tf for the lesson (0.G.4 transient #7).
  patroni_etcd_endpoints = "etcd-1:2379,etcd-2:2379,etcd-3:2379"
}

resource "null_resource" "patroni_bootstrap" {
  count = var.enable_patroni_bootstrap ? 1 : 0

  triggers = {
    tls_ids             = join(",", [for host in keys(local.patroni_nodes_active) : null_resource.patroni_tls[host].id])
    etcd_bootstrap_id   = length(null_resource.etcd_bootstrap) > 0 ? null_resource.etcd_bootstrap[0].id : "disabled"
    scope               = var.patroni_scope
    patroni_bootstrap_v = "1" # v1 (0.G.4) = initial 3-node Patroni cluster bootstrap with PG 17 + etcd3 DCS + watchdog off + scram-sha-256 password hashing.
  }

  depends_on = [null_resource.patroni_tls, null_resource.etcd_bootstrap]

  provisioner "local-exec" {
    when        = create
    interpreter = ["pwsh", "-NoProfile", "-Command"]
    command     = <<-PWSH
      $sshUser   = '${var.oltp_node_user}'
      $sshOpts   = @('-o','ConnectTimeout=10','-o','BatchMode=yes','-o','StrictHostKeyChecking=no')
      $scope     = '${var.patroni_scope}'
      $etcdHosts = '${local.patroni_etcd_endpoints}'
      $timeout   = ${var.oltp_cluster_timeout_minutes}

      $nodes = @(
%{for host, m in local.patroni_nodes_active~}
        @{ Host='${host}'; VmIp='${m.vm_ip}'; PeerIp='${m.peer_ip}' },
%{endfor~}
        $null
      ) | Where-Object { $_ -ne $null }

      Write-Host "[patroni-bootstrap] scope=$scope, $($nodes.Count) Patroni nodes, etcd=$etcdHosts"

      # ─── Stage 1: render patroni.yml on each node + enable service ────────
      foreach ($n in $nodes) {
        $configBody = @"
# Generated by role-overlay-patroni-bootstrap.tf -- Phase 0.G.4
# DO NOT EDIT BY HAND -- terraform overlay re-applies on every apply.
scope: $scope
namespace: /service/
name: $($n.Host)

restapi:
  listen: 0.0.0.0:8008
  connect_address: $($n.VmIp):8008
  certfile: /etc/nexus-patroni/tls/server-cert.pem
  keyfile: /etc/nexus-patroni/tls/server-key.pem
  cafile: /etc/nexus-patroni/tls/ca.pem
  verify_client: optional
  authentication:
    username: nexusops
    password: __PATRONI_REST_PWD__

etcd3:
  hosts: $etcdHosts
  protocol: https
  cacert: /etc/nexus-patroni/tls/ca.pem
  cert: /etc/nexus-patroni/tls/server-cert.pem
  key: /etc/nexus-patroni/tls/server-key.pem
  username: root
  password: __ETCD_ROOT_PWD__

bootstrap:
  dcs:
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
    maximum_lag_on_failover: 1048576
    postgresql:
      use_pg_rewind: true
      use_slots: true
      parameters:
        max_connections: 200
        shared_buffers: 256MB
        wal_level: replica
        hot_standby: "on"
        wal_log_hints: "on"
        max_wal_senders: 10
        max_replication_slots: 10
        wal_keep_size: 256MB
        password_encryption: scram-sha-256
  initdb:
    - encoding: UTF8
    - data-checksums
  pg_hba:
    # Replication allowed from both VMnet10 (backplane, design intent) AND
    # VMnet11 (service) -- Patroni's connect_address is VMnet11 by default,
    # so replicas pg_basebackup from leader via VMnet11. The rule covers
    # both subnets via 192.168.0.0/16. (Transient #11 at 0.G.4 ratification
    # 2026-05-19: original rule only allowed VMnet10 -> "no pg_hba.conf
    # entry for replication connection from host 192.168.70.63".)
    - "hostssl replication replicator 192.168.0.0/16 scram-sha-256"
    - "hostssl all all 192.168.0.0/16 scram-sha-256"
    - "host all all 127.0.0.1/32 trust"
    - "host replication replicator 127.0.0.1/32 trust"
  users:
    nexusops:
      password: __POSTGRES_SUPERUSER_PWD__
      options:
        - superuser
        - createrole
        - createdb

postgresql:
  listen: 0.0.0.0:5432
  connect_address: $($n.VmIp):5432
  data_dir: /var/lib/nexus-patroni/data
  bin_dir: /usr/lib/postgresql/17/bin
  pgpass: /var/lib/nexus-patroni/.pgpass_patroni
  authentication:
    superuser:
      username: postgres
      password: __POSTGRES_SUPERUSER_PWD__
    replication:
      username: replicator
      password: __POSTGRES_REPLICATION_PWD__
    rewind:
      username: rewind
      password: __POSTGRES_REPLICATION_PWD__
  parameters:
    unix_socket_directories: /var/run/nexus-patroni
    ssl: "on"
    ssl_cert_file: /etc/nexus-patroni/tls/server-cert.pem
    ssl_key_file: /etc/nexus-patroni/tls/server-key.pem
    ssl_ca_file: /etc/nexus-patroni/tls/ca.pem
    password_encryption: scram-sha-256

watchdog:
  mode: off

tags:
  nofailover: false
  noloadbalance: false
  clonefrom: false
  nosync: false
"@
        $configB64 = [Convert]::ToBase64String([System.Text.UTF8Encoding]::new($false).GetBytes(($configBody -replace "`r`n","`n")))

        # NOTE: `password_file` is a Patroni 3+ feature: instead of inlining
        # the password into patroni.yml, point at a file with the password as
        # its sole content. Avoids storing creds in patroni.yml (which is
        # otherwise group-readable by postgres).

        # Read the 4 KV-rendered passwords on the target node + sed-substitute
        # them into the patroni.yml template tokens. Patroni 4.0.5's
        # _build_effective_configuration eagerly formats `username:password`
        # at config-load time for restapi.authentication + etcd3 (and likely
        # postgresql.authentication too), expecting LITERAL `password:` keys
        # -- `password_file:` is NOT honored in that code path despite docs.
        # (Transient #10 at 0.G.4 ratification 2026-05-19; KeyError: 'password'.)
        $stage = @"
set -euo pipefail

# Read the 4 KV-rendered password files. All are mode 0400 root:postgres
# (rendered by patroni-tls overlay); sudo cat is required.
ETCD_PWD=`$(sudo cat /etc/nexus-patroni/etcd-root-password)
REST_PWD=`$(sudo cat /etc/nexus-patroni/patroni-rest-password)
SUPER_PWD=`$(sudo cat /etc/nexus-patroni/postgres-superuser-password)
REPL_PWD=`$(sudo cat /etc/nexus-patroni/postgres-replication-password)

for p in "`$ETCD_PWD" "`$REST_PWD" "`$SUPER_PWD" "`$REPL_PWD"; do
  if [ -z "`$p" ]; then
    echo "[patroni-bootstrap stage] ERROR: one of the 4 password files is empty -- patroni-tls overlay may not have rendered yet" >&2
    exit 1
  fi
done

TMP=`$(mktemp)
echo '$configB64' | base64 -d > "`$TMP"
# Substitute the 4 placeholders. Passwords are 32-char hex; no sed regex
# metachar risk. Use `|` separator to avoid colliding with `/` in any paths.
sed -i "s|__ETCD_ROOT_PWD__|`$ETCD_PWD|g; s|__PATRONI_REST_PWD__|`$REST_PWD|g; s|__POSTGRES_SUPERUSER_PWD__|`$SUPER_PWD|g; s|__POSTGRES_REPLICATION_PWD__|`$REPL_PWD|g" "`$TMP"

# Verify no placeholders survived.
if grep -q '__POSTGRES_\|__ETCD_\|__PATRONI_' "`$TMP"; then
  echo "[patroni-bootstrap stage] ERROR: placeholder(s) survived sed substitution" >&2
  grep '__' "`$TMP" >&2
  rm -f "`$TMP"
  exit 1
fi

sudo install -m 0640 -o root -g postgres "`$TMP" /etc/nexus-patroni/patroni.yml
rm -f "`$TMP"

sudo systemctl daemon-reload
sudo systemctl enable nexus-patroni.service
echo CONFIG_OK
"@
        $stageB64 = [Convert]::ToBase64String([System.Text.UTF8Encoding]::new($false).GetBytes($stage))
        $out = (ssh @sshOpts "$sshUser@$($n.VmIp)" "echo '$stageB64' | base64 -d | bash" 2>&1 | Out-String).Trim()
        if ($out -notmatch 'CONFIG_OK') {
          throw "[patroni-bootstrap] $($n.Host): patroni.yml staging failed -- $out"
        }
        Write-Host "[patroni-bootstrap] $($n.Host): patroni.yml rendered + service enabled"
      }

      # Parallel start (Patroni nodes race for the etcd lease; first wins as leader).
      Write-Host "[patroni-bootstrap] starting nexus-patroni.service on all $($nodes.Count) nodes in parallel..."
      $nodes | ForEach-Object -ThrottleLimit 3 -Parallel {
        $n = $_
        $opts = @('-o','ConnectTimeout=10','-o','BatchMode=yes','-o','StrictHostKeyChecking=no')
        ssh @opts "$using:sshUser@$($n.VmIp)" "sudo systemctl start nexus-patroni.service" 2>&1 | Out-Null
      }

      # ─── Stage 2: wait for Leader + 2 Streaming Replica ──────────────────
      Write-Host "[patroni-bootstrap] waiting for cluster to converge (1 Leader + 2 Streaming Replica)..."
      $deadline = (Get-Date).AddMinutes($timeout)
      $leaderHost = $null
      $converged = $false
      $firstNode = $nodes[0]
      while ((Get-Date) -lt $deadline) {
        $listOut = (ssh @sshOpts "$sshUser@$($firstNode.VmIp)" "sudo /usr/local/sbin/nexus-patronictl list --format json 2>/dev/null" 2>&1 | Out-String).Trim()
        if ($listOut -match '^\[') {
          try {
            $cluster = $listOut | ConvertFrom-Json
            $leader = $cluster | Where-Object { $_.Role -eq 'Leader' } | Select-Object -First 1
            $replicas = $cluster | Where-Object { $_.Role -eq 'Replica' -or $_.Role -eq 'Sync Standby' }
            $running = $cluster | Where-Object { $_.State -eq 'running' -or $_.State -eq 'streaming' }
            if ($leader -and $replicas.Count -ge 2 -and $running.Count -ge 3) {
              $leaderHost = $leader.Member
              $converged  = $true
              break
            }
          } catch {
            # bad JSON during early convergence; retry
          }
        }
        Start-Sleep -Seconds 5
      }
      if (-not $converged) {
        foreach ($n in $nodes) {
          $j = (ssh @sshOpts "$sshUser@$($n.VmIp)" "sudo journalctl -u nexus-patroni.service --no-pager -n 30" 2>&1 | Out-String)
          Write-Host "--- journal $($n.Host) ---"
          Write-Host $j
        }
        throw "[patroni-bootstrap] cluster did not converge (1 Leader + 2 Streaming Replica) within $timeout min"
      }
      Write-Host "[patroni-bootstrap] cluster converged: leader=$leaderHost, $($nodes.Count - 1) replicas streaming."

      # ─── Stage 3: create nexusops superuser (Patroni 4 ignores bootstrap.users)
      # Patroni 4 silently drops bootstrap.users (deprecated since 3.x in favor
      # of bootstrap.post_init). The nexusops superuser declared in patroni.yml
      # is never created. Workaround: CREATE USER it directly via the running
      # leader as the postgres superuser (peer-auth via Unix socket, no pwd).
      # Idempotent via `CREATE USER ... IF NOT EXISTS`-equivalent
      # (the DO-block checks pg_roles first).
      # (Transient #12 at 0.G.4 ratification 2026-05-19.)
      $leaderNode = $nodes | Where-Object { $_.Host -eq $leaderHost } | Select-Object -First 1
      Write-Host "[patroni-bootstrap] creating nexusops superuser on leader $leaderHost (Patroni 4 ignores bootstrap.users)..."
      $createUserStage = @'
set -euo pipefail
SUPER_PWD=$(sudo cat /etc/nexus-patroni/postgres-superuser-password)
SOCK_DIR=/var/run/nexus-patroni
sudo -u postgres psql -h "$SOCK_DIR" -U postgres -d postgres -v ON_ERROR_STOP=1 <<SQL
DO \$\$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'nexusops') THEN
    CREATE ROLE nexusops LOGIN SUPERUSER CREATEROLE CREATEDB PASSWORD '$SUPER_PWD';
  ELSE
    ALTER ROLE nexusops WITH LOGIN SUPERUSER CREATEROLE CREATEDB PASSWORD '$SUPER_PWD';
  END IF;
END
\$\$;
SQL
echo "[patroni-bootstrap users] nexusops superuser ensured"
'@
      $createUserB64 = [Convert]::ToBase64String([System.Text.UTF8Encoding]::new($false).GetBytes($createUserStage))
      $createUserOut = (ssh @sshOpts "$sshUser@$($leaderNode.VmIp)" "echo '$createUserB64' | base64 -d | bash" 2>&1 | Out-String)
      if ($LASTEXITCODE -ne 0) {
        Write-Host $createUserOut.Trim()
        throw "[patroni-bootstrap] nexusops user creation failed (rc=$LASTEXITCODE)"
      }
      Write-Host $createUserOut.Trim()

      # ─── Stage 4: psql write/read round-trip via leader ──────────────────
      $rwStage = @'
set -euo pipefail
SUPER_PWD=$(sudo cat /etc/nexus-patroni/postgres-superuser-password)
export PGPASSWORD="$SUPER_PWD"
# psql as nexusops via Unix socket (Patroni runs PG with
# unix_socket_directories=/var/run/nexus-patroni). For leader-write
# verification we use the unix socket so we do not need TLS validation.
SOCK_DIR=/var/run/nexus-patroni
sudo -u postgres psql -h "$SOCK_DIR" -U nexusops -d postgres -tA -c "CREATE TABLE IF NOT EXISTS nexus_smoke (k text PRIMARY KEY, v text);"
sudo -u postgres psql -h "$SOCK_DIR" -U nexusops -d postgres -tA -c "INSERT INTO nexus_smoke (k, v) VALUES ('bootstrap', '$(date -u +%FT%TZ)') ON CONFLICT (k) DO UPDATE SET v = EXCLUDED.v;"
VAL=$(sudo -u postgres psql -h "$SOCK_DIR" -U nexusops -d postgres -tA -c "SELECT v FROM nexus_smoke WHERE k = 'bootstrap';")
if [ -z "$VAL" ]; then
  echo "[patroni-bootstrap rw] ERROR: insert-then-read returned empty" >&2
  exit 1
fi
echo "[patroni-bootstrap rw] insert+read on leader OK (val=$VAL)"
'@
      $rwB64 = [Convert]::ToBase64String([System.Text.UTF8Encoding]::new($false).GetBytes($rwStage))
      $rwOut = (ssh @sshOpts "$sshUser@$($leaderNode.VmIp)" "echo '$rwB64' | base64 -d | bash" 2>&1 | Out-String)
      if ($LASTEXITCODE -ne 0) {
        Write-Host $rwOut.Trim()
        throw "[patroni-bootstrap] psql round-trip on leader failed (rc=$LASTEXITCODE)"
      }
      Write-Host $rwOut.Trim()

      Write-Host "[patroni-bootstrap] cluster ready: leader=$leaderHost, $($nodes.Count) nodes streaming on TLS."
    PWSH
  }
}
