# 12-firstboot-stage.ps1 -- pre-stage firstboot infrastructure for the
# oltp-sqlserver-node template.
#
# Mirrors the Linux pattern (packer/_shared/ansible/roles/oltp_firstboot/files/
# oltp-node-firstboot.sh) -- a clone-time-aware script that on each cloned
# VM's first boot:
#   1. Detects which node it is from its VMnet11 IP (which is pinned by the
#      foundation env's dhcp-host reservation -> .70.11/.12/.13/.14 maps to
#      sql-fci-1/2/sql-ag-rep-1/2).
#   2. Renames the computer accordingly (Rename-Computer -Restart).
#   3. Writes C:\ProgramData\nexus\sql\node-identity.env with role + cluster
#      facts for downstream PowerShell scripts to consume.
#   4. Configures the VMnet10 (backplane) static IP per the role + IP plan
#      from network.md (10.10.x scheme: SQL Server = 10.10.11..14).
#
# Runs as a one-shot scheduled task on first OOBE boot, then deletes itself
# so subsequent reboots are no-ops.
#
# We STAGE the firstboot script here (write to C:\ProgramData\nexus\sql\
# firstboot.ps1 + register the scheduled task to run it at first user
# logon). The actual rename/IP-config happens at clone first-boot, NOT
# at this bake step.

$ErrorActionPreference = 'Stop'

Write-Host "=== 12-firstboot-stage: staging firstboot infrastructure ==="

# ---------------------------------------------------------------------
# Step 1: Create the per-engine staging directory at C:\ProgramData\nexus\sql\.
# Mirrors the Linux /etc/nexus-<engine>/ pattern. ProgramData is the
# Windows canon for service-owned data (vs C:\Program Files which is for
# binaries).
# ---------------------------------------------------------------------
$stagingDir = 'C:\ProgramData\nexus\sql'
$tlsDir     = Join-Path $stagingDir 'tls'
$credsDir   = Join-Path $stagingDir 'creds'
$logsDir    = Join-Path $stagingDir 'logs'

foreach ($d in @($stagingDir, $tlsDir, $credsDir, $logsDir)) {
    if (-not (Test-Path $d)) {
        New-Item -ItemType Directory -Force -Path $d | Out-Null
    }
    # ACL: only SYSTEM + BUILTIN\Administrators + the eventual GMSA can
    # read/write. nexusadmin has admin so inherits via Administrators.
    # The GMSA gets added later by terraform's role-overlay-sqlserver-
    # vault-agents.tf once domain-join completes.
    $acl = Get-Acl $d
    $acl.SetAccessRuleProtection($true, $false)
    $sysRule    = New-Object System.Security.AccessControl.FileSystemAccessRule(
        'NT AUTHORITY\SYSTEM', 'FullControl', 'ContainerInherit,ObjectInherit', 'None', 'Allow')
    $adminsRule = New-Object System.Security.AccessControl.FileSystemAccessRule(
        'BUILTIN\Administrators', 'FullControl', 'ContainerInherit,ObjectInherit', 'None', 'Allow')
    $acl.AddAccessRule($sysRule)
    $acl.AddAccessRule($adminsRule)
    Set-Acl $d $acl
}
Write-Host "  - staging dirs created at $stagingDir (tls/, creds/, logs/)"

# ---------------------------------------------------------------------
# Step 2: Write the firstboot script. It runs once on first OOBE boot,
# detects the node identity from its VMnet11 IP, renames the computer,
# configures the VMnet10 static IP, writes node-identity.env, then
# self-deletes the scheduled task.
#
# IP-to-hostname map (per network.md + vms.yaml):
#   192.168.70.11 -> sql-fci-1     (FCI node 1; VMnet10 10.10.11)
#   192.168.70.12 -> sql-fci-2     (FCI node 2; VMnet10 10.10.12)
#   192.168.70.13 -> sql-ag-rep-1  (AG replica 1; VMnet10 10.10.13)
#   192.168.70.14 -> sql-ag-rep-2  (AG replica 2; VMnet10 10.10.14)
#
# Why infer from IP (not VM name): the source ws2025-desktop.vmx has VM
# name "ws2025-desktop"; modules/vm clones it as the new VM name (e.g.
# "sql-fci-1") at the VMware layer but Windows's ComputerName is still
# the sysprep-set default (WIN-XXXXX). Rename-Computer + restart is
# needed to align Windows ComputerName with the VMware VM name. We
# infer from IP because IP is the only reliable identity-anchor at
# Windows-first-boot (the VMware VM name isn't queryable from inside
# the guest without VMware Tools introspection).
# ---------------------------------------------------------------------
$firstbootScript = @'
# C:\ProgramData\nexus\sql\firstboot.ps1
# Generated by packer/oltp-sqlserver-node/scripts/12-firstboot-stage.ps1.
# Runs once on first OOBE boot via NexusSqlFirstboot scheduled task.

$ErrorActionPreference = 'Continue'
$logFile = 'C:\ProgramData\nexus\sql\logs\firstboot.log'
function Log { param($msg) Add-Content -Path $logFile -Value "$(Get-Date -Format 'o') $msg" }

Log "=== firstboot start ==="

# --- 1. Detect VMnet11 IP -------------------------------------------------
# The .70.x adapter is the one bound to a 192.168.70.0/24 IP. dhcp-host
# reservation on nexus-gateway pinned this VM's MAC to .11/.12/.13/.14.
$vmnet11Ip = Get-NetIPAddress -AddressFamily IPv4 -ErrorAction SilentlyContinue |
    Where-Object { $_.IPAddress -like '192.168.70.*' } |
    Select-Object -First 1 -ExpandProperty IPAddress

if (-not $vmnet11Ip) {
    Log "ERROR: no VMnet11 IP found yet; the dhcp-host reservation on nexus-gateway may not have latched. Retrying in 30s (scheduled task will re-fire if needed)."
    exit 1
}
Log "VMnet11 IP detected: $vmnet11Ip"

# --- 2. Map IP -> role + hostname + VMnet10 backplane IP ------------------
$identityMap = @{
    '192.168.70.11' = @{ Hostname = 'sql-fci-1';    Role = 'fci';        Vmnet10 = '192.168.10.11' }
    '192.168.70.12' = @{ Hostname = 'sql-fci-2';    Role = 'fci';        Vmnet10 = '192.168.10.12' }
    '192.168.70.13' = @{ Hostname = 'sql-ag-rep-1'; Role = 'ag-replica'; Vmnet10 = '192.168.10.13' }
    '192.168.70.14' = @{ Hostname = 'sql-ag-rep-2'; Role = 'ag-replica'; Vmnet10 = '192.168.10.14' }
}
$identity = $identityMap[$vmnet11Ip]
if (-not $identity) {
    Log "ERROR: VMnet11 IP $vmnet11Ip not in identityMap. This VM didn't get a pinned dhcp-host reservation; verify foundation env applied with the SQL MAC reservations."
    exit 1
}
Log "Identity: $($identity.Hostname) ($($identity.Role); VMnet10=$($identity.Vmnet10))"

# --- 3. Write node-identity.env -----------------------------------------
$identityEnv = @"
NEXUS_NODE_HOSTNAME=$($identity.Hostname)
NEXUS_NODE_ROLE=$($identity.Role)
NEXUS_NODE_CLUSTER=sqlserver
NEXUS_NODE_VMNET11_IP=$vmnet11Ip
NEXUS_NODE_VMNET10_IP=$($identity.Vmnet10)
"@
Set-Content -Path 'C:\ProgramData\nexus\sql\node-identity.env' -Value $identityEnv -Encoding utf8
Log "Wrote node-identity.env"

# --- 4. Configure VMnet10 backplane static IP ---------------------------
# The VMnet10 NIC was added at clone time by modules/vm. Find it (the one
# WITHOUT a 192.168.70.x IP, since VMnet11 has that). Assign static .10.x.
$vmnet10Nic = Get-NetAdapter -Physical |
    Where-Object {
        $ipAddrs = ($_ | Get-NetIPAddress -AddressFamily IPv4 -ErrorAction SilentlyContinue).IPAddress
        $ipAddrs -notlike '192.168.70.*' -and $_.Status -eq 'Up'
    } |
    Select-Object -First 1

if ($vmnet10Nic) {
    # Remove any existing IPv4 config on this NIC (likely APIPA 169.254.x.x).
    Get-NetIPAddress -InterfaceAlias $vmnet10Nic.Name -AddressFamily IPv4 -ErrorAction SilentlyContinue |
        Where-Object { -not $_.IPAddress.StartsWith('192.168.10.') } |
        Remove-NetIPAddress -Confirm:$false -ErrorAction SilentlyContinue
    # Set static .10.x with no gateway (backplane is isolated; no egress).
    try {
        New-NetIPAddress -InterfaceAlias $vmnet10Nic.Name `
            -IPAddress $identity.Vmnet10 -PrefixLength 24 -ErrorAction Stop | Out-Null
        Log "VMnet10 backplane configured: $($identity.Vmnet10)/24 on $($vmnet10Nic.Name)"
    } catch {
        # Idempotent: if already configured, ignore.
        if ($_.Exception.Message -notmatch 'already exists') {
            Log "WARN: VMnet10 IP config failed: $($_.Exception.Message)"
        } else {
            Log "VMnet10 IP $($identity.Vmnet10) already configured (idempotent)"
        }
    }
} else {
    Log "WARN: no VMnet10 NIC found in Up state. This is expected on FIRST first-boot before modules/vm has added the second NIC; firstboot task will retry on next reboot."
}

# --- 5. Rename the computer + plan restart -----------------------------
$currentName = $env:COMPUTERNAME
if ($currentName -ne $identity.Hostname) {
    Log "Renaming computer from $currentName to $($identity.Hostname); restart scheduled."
    try {
        Rename-Computer -NewName $identity.Hostname -Force -ErrorAction Stop
        # Schedule restart in 60s so this script can complete + log.
        Start-Process -FilePath 'shutdown.exe' -ArgumentList '/r','/t','60','/c','"NexusSqlFirstboot: rename completed; restart"' -NoNewWindow
        Log "Restart scheduled at T+60s"
    } catch {
        Log "ERROR: Rename-Computer failed: $($_.Exception.Message)"
        exit 1
    }
} else {
    Log "ComputerName already $($identity.Hostname); no rename needed."
}

# --- 6. Self-disable the scheduled task ---------------------------------
# Once we've renamed + IP-configured, this script doesn't need to re-fire.
# terraform-time overlays read node-identity.env directly.
try {
    Unregister-ScheduledTask -TaskName 'NexusSqlFirstboot' -Confirm:$false -ErrorAction Stop
    Log "Scheduled task NexusSqlFirstboot disabled (self-cleanup)"
} catch {
    Log "WARN: Unregister-ScheduledTask failed: $($_.Exception.Message)"
}

Log "=== firstboot complete ==="
'@

$firstbootPath = Join-Path $stagingDir 'firstboot.ps1'
Set-Content -Path $firstbootPath -Value $firstbootScript -Encoding utf8
Write-Host "  - firstboot.ps1 staged at $firstbootPath"

# ---------------------------------------------------------------------
# Step 3: Register the firstboot scheduled task. Fires at user logon as
# SYSTEM (so it can rename + configure IP without needing an
# interactive session). The mini-OOBE auto-logons the nexusadmin
# account once after sysprep, which triggers the AtLogOn trigger.
# Self-deletes via Unregister-ScheduledTask in the script itself.
# ---------------------------------------------------------------------
$action = New-ScheduledTaskAction -Execute 'powershell.exe' `
    -Argument "-NoProfile -ExecutionPolicy Bypass -File `"$firstbootPath`""
# Trigger: AtLogon (any user). Mini-OOBE auto-logs in nexusadmin on first
# boot post-sysprep, which fires this.
$trigger = New-ScheduledTaskTrigger -AtLogOn
$principal = New-ScheduledTaskPrincipal -UserId 'SYSTEM' -RunLevel Highest -LogonType ServiceAccount
$settings = New-ScheduledTaskSettingsSet `
    -AllowStartIfOnBatteries `
    -DontStopIfGoingOnBatteries `
    -StartWhenAvailable `
    -ExecutionTimeLimit (New-TimeSpan -Minutes 10)

Register-ScheduledTask -TaskName 'NexusSqlFirstboot' `
    -Action $action -Trigger $trigger -Principal $principal -Settings $settings `
    -Description 'NexusPlatform 0.G.7 first-boot: detect node identity from VMnet11 IP, rename computer, configure VMnet10 backplane IP. Self-deletes after success.' `
    -Force | Out-Null

Write-Host "  - scheduled task NexusSqlFirstboot registered (fires AtLogon as SYSTEM)"

# ---------------------------------------------------------------------
# Step 4: Create the staging marker. Used by terraform's overlays to
# probe whether the firstboot infrastructure is staged + ready.
# ---------------------------------------------------------------------
$marker = @"
{
  "staged_at": "$(Get-Date -Format 'o')",
  "template": "oltp-sqlserver-node",
  "phase": "0.G.7",
  "scripts": ["firstboot.ps1"],
  "scheduled_tasks": ["NexusSqlFirstboot"],
  "dirs": ["C:\\ProgramData\\nexus\\sql\\{,tls/,creds/,logs/}"]
}
"@
Set-Content -Path (Join-Path $stagingDir 'staged.json') -Value $marker -Encoding utf8

Write-Host "=== 12-firstboot-stage: complete; staged.json marker written ==="
