# Phase 0.N -- per-host engine config + systemd unit + service start.
#
# Three role variants:
#   - configsvr (cfg-1/2/3): mongod --configsvr --replSet config --port 27019
#   - shardsvr  (shard-1/2 nodes): mongod --shardsvr --replSet <rs> --port 27018
#   - mongos    (mongos-1/2): mongos --configdb config/<cfg-IPs> --port 27017
#
# The shared nexus-mongo.service unit from the Packer template runs mongod
# with /etc/nexus-mongo/mongod.conf. For mongos we install a NEW
# nexus-mongos.service that runs mongos with /etc/nexus-mongo/mongos.conf
# (the engines listen on different ports + bind to different config paths so
# they can coexist on the same template).
#
# Auth: keyFile member auth + (0.N.1) wire mTLS. net.tls (requireTLS +
# certificateKeyFile/CAFile, allowConnectionsWithoutCertificates:false) is
# injected under `net:` when var.enable_mongo_tls is on -- certs rendered by
# role-overlay-mongo-tls.tf (this overlay depends_on it). clusterAuthMode stays
# keyFile (member identity); TLS adds wire encryption only.
# When keyFile is present, MongoDB requires security.authorization=enabled.
# That means the first connection to the still-empty admin DB must use the
# localhost-exception... BUT 0.G.2 found that MongoDB 8.0 + keyFile +
# authorization=enabled disables the localhost-exception EVEN if you set
# enableLocalhostAuthBypass. So we bootstrap via __system cluster auth using
# the keyFile content as the password (same workaround as 0.G.2).

locals {
  # 0.N.1 wire mTLS: the net.tls sub-block, injected under `net:` in both the
  # mongod (cfg/shard) and mongos config shapes when var.enable_mongo_tls is on.
  # requireTLS + mutual client certs (allowConnectionsWithoutCertificates:false)
  # -- parity with the 0.G.2 mongo RS. Cert files rendered by
  # role-overlay-mongo-tls.tf (server.pem = leaf+key, ca.crt = intermediate+root).
  # clusterAuthMode stays keyFile (member auth); TLS adds wire encryption only.
  mongo_tls_net_lines = var.enable_mongo_tls ? [
    "  tls:",
    "    mode: requireTLS",
    "    certificateKeyFile: /etc/nexus-mongo/tls/server.pem",
    "    CAFile: /etc/nexus-mongo/tls/ca.crt",
    "    allowConnectionsWithoutCertificates: false",
    "    disabledProtocols: TLS1_0,TLS1_1",
  ] : []

  # Per-host engine config. Cfg + shardsvr use mongod.conf shape; mongos
  # uses mongos.conf shape (no replication/storage/dbPath blocks).
  mongo_sharded_config_rendered = {
    for host, spec in local.sharded_nodes_active : host => (
      spec.role == "mongos" ?
      join("\n", concat([
        "# Generated by oltp-mongo-sharded/role-overlay-mongo-config.tf (mongos)",
        "# role=mongos -- stateless query router; configdb points at the config-server RS.",
        "",
        "net:",
        "  bindIp: 0.0.0.0,::1",
        "  port: ${spec.port}",
        ], local.mongo_tls_net_lines, [
        "",
        "security:",
        "  keyFile: /etc/nexus-mongo/keyfile",
        "  clusterAuthMode: keyFile",
        "",
        "sharding:",
        "  configDB: ${local.config_db_uri}",
        "",
        "systemLog:",
        "  destination: file",
        "  path: /var/log/nexus-mongo/mongos.log",
        "  logAppend: true",
        "  verbosity: 0",
        "",
        "processManagement:",
        "  fork: false",
        "  pidFilePath: /var/run/nexus-mongo/mongos.pid",
        "",
      ])) :
      join("\n", concat([
        "# Generated by oltp-mongo-sharded/role-overlay-mongo-config.tf (mongod)",
        "# role=${spec.role} rs=${spec.rs_name} port=${spec.port}",
        "",
        "net:",
        "  bindIp: 0.0.0.0,::1",
        "  port: ${spec.port}",
        ], local.mongo_tls_net_lines, [
        "",
        "replication:",
        "  replSetName: ${spec.rs_name}",
        "",
        "security:",
        "  keyFile: /etc/nexus-mongo/keyfile",
        "  authorization: enabled",
        "  clusterAuthMode: keyFile",
        "",
        "sharding:",
        "  clusterRole: ${spec.role}",
        "",
        "storage:",
        "  dbPath: /var/lib/nexus-mongo",
        "  wiredTiger:",
        "    engineConfig:",
        "      cacheSizeGB: 0.5",
        "",
        "systemLog:",
        "  destination: file",
        "  path: /var/log/nexus-mongo/mongod.log",
        "  logAppend: true",
        "  verbosity: 0",
        "",
        "processManagement:",
        "  fork: false",
        "  pidFilePath: /var/run/nexus-mongo/mongod.pid",
        "",
      ]))
    )
  }

  # systemd unit for mongos (data nodes use the pre-baked nexus-mongo.service).
  mongos_systemd_unit = <<-UNIT
    [Unit]
    Description=Nexus MongoDB sharded cluster mongos router (Phase 0.N)
    Documentation=https://www.mongodb.com/docs/manual/reference/program/mongos/
    Requires=network-online.target
    After=network-online.target oltp-node-firstboot.service

    [Service]
    Type=simple
    User=mongodb
    Group=mongodb
    RuntimeDirectory=nexus-mongo
    RuntimeDirectoryMode=0750
    LogsDirectory=nexus-mongo
    LogsDirectoryMode=0750
    ExecStart=/usr/bin/mongos --config /etc/nexus-mongo/mongos.conf
    Restart=on-failure
    RestartSec=5
    KillMode=process
    LimitNOFILE=64000

    [Install]
    WantedBy=multi-user.target
  UNIT
}

resource "null_resource" "mongo_config" {
  for_each = var.enable_mongo_config ? local.sharded_nodes_active : {}

  triggers = {
    keyfile_id = null_resource.mongo_keyfile[each.key].id
    tls_id     = var.enable_mongo_tls ? null_resource.mongo_sharded_tls[each.key].id : "disabled"
    role       = each.value.role
    port       = each.value.port
    rs_name    = each.value.rs_name
    conf_sha   = sha256(local.mongo_sharded_config_rendered[each.key])
    overlay_v  = "2" # v2 (0.N.1) = net.tls (requireTLS) injected; depends_on the TLS overlay so server.pem/ca.crt exist before mongod restarts.

    destroy_vm_ip    = each.value.vmnet11
    destroy_ssh_user = var.oltp_node_user
    destroy_role     = each.value.role
  }

  depends_on = [null_resource.mongo_keyfile, null_resource.mongo_sharded_tls]

  provisioner "local-exec" {
    when        = create
    interpreter = ["pwsh", "-NoProfile", "-Command"]
    command     = <<-PWSH
      $hostName = '${each.key}'
      $ip       = '${each.value.vmnet11}'
      $role     = '${each.value.role}'
      $port     = ${each.value.port}
      $sshUser  = '${var.oltp_node_user}'
      $timeout  = ${var.oltp_cluster_timeout_minutes}
      $sshOpts  = @('-o','ConnectTimeout=10','-o','BatchMode=yes','-o','StrictHostKeyChecking=no')

      $rendered = @'
${local.mongo_sharded_config_rendered[each.key]}
'@
      $rendered = $rendered -replace "`r`n","`n"
      $confB64  = [Convert]::ToBase64String([System.Text.UTF8Encoding]::new($false).GetBytes($rendered))

      Write-Host ""
      Write-Host "[config $hostName] role=$role port=$port -- writing engine config + (re)starting service"

      if ($role -eq 'mongos') {
        # mongos needs new unit + mongos.conf + service start. nexus-mongo.service
        # (mongod default) is masked + disabled on this host.
        $unitContent = @'
${local.mongos_systemd_unit}
'@
        $unitContent = $unitContent -replace "`r`n","`n"
        $unitB64 = [Convert]::ToBase64String([System.Text.UTF8Encoding]::new($false).GetBytes($unitContent))

        $stage = @"
set -euo pipefail

# Install dirs (mongos uses the same nexus-mongo log dir as mongod).
sudo install -d -o mongodb -g mongodb -m 0750 /etc/nexus-mongo
sudo install -d -o mongodb -g mongodb -m 0750 /var/log/nexus-mongo
sudo install -d -o mongodb -g mongodb -m 0755 /var/run/nexus-mongo

# mongos.conf
echo '$confB64' | base64 -d | sudo tee /etc/nexus-mongo/mongos.conf > /dev/null
sudo chown root:mongodb /etc/nexus-mongo/mongos.conf
sudo chmod 0640 /etc/nexus-mongo/mongos.conf

# nexus-mongos.service unit
echo '$unitB64' | base64 -d | sudo tee /etc/systemd/system/nexus-mongos.service > /dev/null
sudo chown root:root /etc/systemd/system/nexus-mongos.service
sudo chmod 0644 /etc/systemd/system/nexus-mongos.service

# Make sure mongod is NOT running on this host (mongos host).
sudo systemctl disable --now nexus-mongo.service 2>/dev/null || true

sudo systemctl daemon-reload
sudo systemctl enable nexus-mongos.service
sudo systemctl restart nexus-mongos.service
echo CONFIG_OK
"@
      } else {
        # mongod (cfg or shard). Write mongod.conf + start nexus-mongo.service.
        $stage = @"
set -euo pipefail
sudo install -d -o mongodb -g mongodb -m 0750 /etc/nexus-mongo
sudo install -d -o mongodb -g mongodb -m 0750 /var/lib/nexus-mongo
sudo install -d -o mongodb -g mongodb -m 0750 /var/log/nexus-mongo
sudo install -d -o mongodb -g mongodb -m 0755 /var/run/nexus-mongo

echo '$confB64' | base64 -d | sudo tee /etc/nexus-mongo/mongod.conf > /dev/null
sudo chown root:mongodb /etc/nexus-mongo/mongod.conf
sudo chmod 0640 /etc/nexus-mongo/mongod.conf

sudo systemctl daemon-reload
sudo systemctl enable nexus-mongo.service
sudo systemctl restart nexus-mongo.service
echo CONFIG_OK
"@
      }

      $stageLf = $stage -replace "`r`n", "`n"
      $stageOut = ($stageLf | ssh @sshOpts "$sshUser@$ip" "tr -d '\r' | bash -s" 2>&1 | Out-String)
      if ($LASTEXITCODE -ne 0 -or $stageOut -notmatch 'CONFIG_OK') {
        Write-Host $stageOut.Trim()
        throw "[config $hostName] config render / service start failed"
      }

      # Wait for the service to come up. mongod (cfg/shard) binds its port
      # immediately, so we require active + listening. mongos is DIFFERENT: it
      # cannot bind its client port (27017) until it has loaded the sharding
      # metadata from the config-server RS -- and that RS is only initialized
      # by the LATER role-overlay-mongo-rs-initiate.tf. So a mongos node here
      # is `active` (Type=simple process running, internally retrying the
      # config-server connection, NRestarts=0) but NOT yet listening. Requiring
      # `listening` for mongos would deadlock: config waits for mongos:27017,
      # mongos waits for the config RS, rs-initiate waits for config to finish.
      # Resolution: for mongos we only confirm the unit reached `active` (no
      # crash); operational readiness (accepting commands on 27017) is gated by
      # the add-shards overlay's ping loop, which runs AFTER rs-initiate brings
      # the config RS online -- at which point mongos finishes startup + binds
      # 27017 on its own (no restart needed). Diagnosed live at 0.N ratification
      # 2026-05-30 (handbook §3.N transient N6).
      $svc = if ($role -eq 'mongos') { 'nexus-mongos.service' } else { 'nexus-mongo.service' }
      $deadline = (Get-Date).AddMinutes($timeout)
      $ok = $false
      if ($role -eq 'mongos') {
        Write-Host "[config $hostName] waiting for $svc active (mongos binds 27017 later, after the config-server RS is initiated)..."
        while ((Get-Date) -lt $deadline) {
          $active = (ssh @sshOpts "$sshUser@$ip" "systemctl is-active $svc" 2>&1 | Out-String).Trim()
          if ($active -eq 'active') { $ok = $true; break }
          if ($active -eq 'failed') { break }
          Start-Sleep -Seconds 5
        }
        if (-not $ok) {
          $journal = (ssh @sshOpts "$sshUser@$ip" "sudo journalctl -u $svc --no-pager -n 30" 2>&1 | Out-String)
          Write-Host $journal
          throw "[config $hostName] $svc did not reach active within $timeout min"
        }
        Write-Host "[config $hostName] $svc active (port 27017 will bind after rs-initiate; readiness gated by add-shards)"
      } else {
        Write-Host "[config $hostName] waiting for $svc active + port $port listening..."
        while ((Get-Date) -lt $deadline) {
          $active = (ssh @sshOpts "$sshUser@$ip" "systemctl is-active $svc" 2>&1 | Out-String).Trim()
          if ($active -eq 'active') {
            # Port check via /proc/net/tcp parsing -- simpler than installing ss/netstat.
            $portHex = '{0:X4}' -f $port
            $listening = (ssh @sshOpts "$sshUser@$ip" "grep -E ':$portHex 00000000:0000 0A' /proc/net/tcp /proc/net/tcp6 2>/dev/null | wc -l" 2>&1 | Out-String).Trim()
            if ($listening -match '^[1-9]') { $ok = $true; break }
          }
          Start-Sleep -Seconds 5
        }
        if (-not $ok) {
          $journal = (ssh @sshOpts "$sshUser@$ip" "sudo journalctl -u $svc --no-pager -n 30" 2>&1 | Out-String)
          Write-Host $journal
          throw "[config $hostName] $svc did not become active+listening within $timeout min"
        }
        Write-Host "[config $hostName] $svc active + port $port listening"
      }
    PWSH
  }

  # Destroy: stop service + remove conf. /var/lib/nexus-mongo preserved.
  provisioner "local-exec" {
    when        = destroy
    interpreter = ["pwsh", "-NoProfile", "-Command"]
    command     = <<-PWSH
      $hostName = '${each.key}'
      $vmIp     = '${self.triggers.destroy_vm_ip}'
      $sshUser  = '${self.triggers.destroy_ssh_user}'
      $role     = '${self.triggers.destroy_role}'
      $svc      = if ($role -eq 'mongos') { 'nexus-mongos.service' } else { 'nexus-mongo.service' }
      $sshOpts  = @('-o','ConnectTimeout=5','-o','BatchMode=yes','-o','StrictHostKeyChecking=no')
      Write-Host "[config destroy] $${hostName}: stopping $svc"
      ssh @sshOpts "$sshUser@$vmIp" "sudo systemctl disable --now $svc 2>/dev/null; sudo rm -f /etc/nexus-mongo/mongod.conf /etc/nexus-mongo/mongos.conf /etc/systemd/system/nexus-mongos.service; sudo systemctl daemon-reload" 2>$null
      exit 0
    PWSH
  }
}
