/*
 * role-overlay-redis-config.tf -- Phase 0.G.1 -- render redis.conf + start
 *
 * Per-host /etc/nexus-redis/redis.conf render + nexus-redis.service enable
 * + start + per-node TLS PING verification. Runs AFTER redis-tls has the
 * cert files in place at /etc/nexus-redis/tls/{server.crt,server.key,ca.crt}
 * (depends_on chain enforces ordering).
 *
 * --- Config shape (mTLS-only from cold start) ---
 *
 * Network:
 *   - bind 0.0.0.0 -::*       Listen on all interfaces (build host on
 *                             192.168.70.1 needs reach via VMnet11; cluster
 *                             peers reach via the same VMnet11 IP)
 *   - port 0                  Plain port DISABLED. Only TLS accepted.
 *   - tls-port 6379           Mutual TLS on the canonical Redis port.
 *   - tls-cluster yes         Cluster bus (16379) is also mTLS.
 *   - tls-auth-clients yes    Every client must present a cert (the redis-
 *                             server PKI role has client_flag=true so the
 *                             broker's own cert doubles as its client
 *                             identity for self-PING + intra-cluster bus).
 *
 * Cluster:
 *   - cluster-enabled yes
 *   - cluster-config-file /var/lib/nexus-redis/nodes.conf
 *                             Persisted cluster topology -- node IDs +
 *                             shard map. Survives restart.
 *   - cluster-node-timeout 5000   ms before a node is marked PFAIL
 *   - cluster-announce-ip <VMnet11 IP>   What this node tells peers + clients
 *                                        to reach it on. Per-host (the only
 *                                        per-host directive).
 *   - cluster-announce-port 6379
 *   - cluster-announce-bus-port 16379
 *
 * Why VMnet11 (not the VMnet10 backplane) for both data + cluster bus:
 *   Simplest config. Build-host clients (on 192.168.70.x) can reach every
 *   node. Cluster traffic in a 6-node lab is negligible -- the backplane
 *   benefit is real for kafka's 100s-of-MB-per-second replication, not for
 *   redis. The dual-NIC + nftables-backplane VMnet10 trust is preserved
 *   for future scale-out flexibility (e.g. `cluster-announce-bus-ip` if a
 *   later sub-phase wants cluster bus on the backplane; Redis 7.2+).
 *
 * Persistence:
 *   - appendonly yes          AOF for durability. Sufficient for lab; a
 *                             later phase can add `save` + RDB.
 *   - dir /var/lib/nexus-redis    Data + nodes.conf + AOF live here.
 *
 * --- Idempotency ---
 *
 * Re-render is unconditional (content-keyed trigger via the rendered text
 * hash). On re-run we drop the same redis.conf, restart the service if its
 * content changed (driven by the hash trigger), and re-verify TLS PING. The
 * service restart is sequential per-host -- this overlay deliberately uses
 * `systemctl restart` (NOT `kill -HUP`) on a config change because Redis
 * does not reload TLS material on SIGHUP, and the simplest "ensure config
 * matches" semantic is a restart. In steady state (cert + config unchanged)
 * the restart is a no-op-fast.
 *
 * --- Smoke / verify ---
 *
 * After enable+start: probe `redis-cli -h 127.0.0.1 -p 6379 --tls --cacert
 * ... --cert ... --key ... PING` returns PONG. Self-mTLS via the same cert
 * proves: (a) the cert/key/ca are valid and chain-trusted; (b) the service
 * is listening on the TLS port; (c) mutual auth works.
 *
 * Reachability invariant: nftables ruleset opens 6379 + 16379 on VMnet11
 * (the nftables-backplane overlay). This overlay does not change network
 * exposure.
 *
 * Selective ops: var.enable_redis_config AND var.enable_redis_tls.
 */

locals {
  redis_config_per_host = {
    "redis-1" = { vmnet10 = "192.168.10.81", vmnet11 = "192.168.70.81" }
    "redis-2" = { vmnet10 = "192.168.10.82", vmnet11 = "192.168.70.82" }
    "redis-3" = { vmnet10 = "192.168.10.83", vmnet11 = "192.168.70.83" }
    "redis-4" = { vmnet10 = "192.168.10.84", vmnet11 = "192.168.70.84" }
    "redis-5" = { vmnet10 = "192.168.10.87", vmnet11 = "192.168.70.87" }
    "redis-6" = { vmnet10 = "192.168.10.89", vmnet11 = "192.168.70.89" }
  }

  redis_config_active = {
    for host, spec in local.redis_config_per_host : host => spec
    if(
      var.enable_redis && var.enable_redis_config && var.enable_redis_tls
      && lookup(local.redis_tls_active, host, null) != null
    )
  }

  # Per-host rendered redis.conf. Cluster directives + per-host announce IP;
  # everything else is identical across the 6 nodes.
  redis_conf_rendered = {
    for host, spec in local.redis_config_active : host => join("\n", [
      "# Generated by nexus-infra-oltp/terraform/envs/oltp/role-overlay-redis-config.tf",
      "# Phase 0.G.1 -- redis-cluster mTLS. Do not edit by hand.",
      "# Host: ${host}   announce-ip: ${spec.vmnet11}",
      "",
      "# --- Network ---",
      "bind 0.0.0.0 -::*",
      "port 0",
      "tls-port 6379",
      "# Redis 'protected mode' refuses non-loopback connections when no",
      "# requirepass is set -- it triggers even on TLS connections from a",
      "# node to its own VMnet11 IP (the cluster-create scenario), erroring",
      "# `DENIED Redis is running in protected mode`. Disabling it here is",
      "# safe because defense-in-depth is already strong: (1) nftables",
      "# restricts 6379+16379 to VMnet11 lab traffic; (2) tls-port + port 0",
      "# means only TLS connections are accepted; (3) tls-auth-clients yes",
      "# requires a valid client cert chained to the lab CA. Adding a",
      "# requirepass on top would be redundant and complicate cluster bus",
      "# auth (which would also need masterauth + replica auth).",
      "protected-mode no",
      "",
      "# --- TLS ---",
      "tls-cert-file       /etc/nexus-redis/tls/server.crt",
      "tls-key-file        /etc/nexus-redis/tls/server.key",
      "tls-ca-cert-file    /etc/nexus-redis/tls/ca.crt",
      "tls-cluster         yes",
      "tls-replication     yes",
      "tls-auth-clients    yes",
      "tls-protocols       \"TLSv1.2 TLSv1.3\"",
      "",
      "# --- Cluster ---",
      "cluster-enabled         yes",
      "cluster-config-file     /var/lib/nexus-redis/nodes.conf",
      "cluster-node-timeout    5000",
      "cluster-announce-ip     ${spec.vmnet11}",
      "cluster-announce-port   6379",
      "cluster-announce-bus-port 16379",
      "",
      "# --- Persistence ---",
      "appendonly  yes",
      "dir         /var/lib/nexus-redis",
      "",
      "# --- Logging + lifecycle (systemd manages) ---",
      "daemonize   no",
      "supervised  systemd",
      "logfile     /var/log/nexus-redis/redis.log",
      "pidfile     /var/run/nexus-redis/redis.pid",
      "loglevel    notice",
      "",
    ])
  }
}

resource "null_resource" "redis_config" {
  for_each = local.redis_config_active

  triggers = {
    tls_id         = null_resource.redis_tls[each.key].id
    vmnet11        = each.value.vmnet11
    conf_sha       = sha256(local.redis_conf_rendered[each.key])
    redis_config_v = "2" # v2 (0.G.1 ratification fix 2026-05-17) = added `protected-mode no` -- Redis 8.0 ships protected mode on by default; without a requirepass it rejects connections from non-loopback addresses, including a node's own VMnet11 IP. That trips `redis-cli --cluster create` (which connects to each node's external IP from the bootstrap node) with `DENIED Redis is running in protected mode`. Safe to disable: nftables firewalls 6379+16379 to VMnet11, tls-port + port 0 forces TLS-only, tls-auth-clients yes requires a valid client cert. v1 = initial straight-to-mTLS config without protected-mode override (the Redis 8.0 default tripped at the cluster-create step).

    destroy_vm_ip    = each.value.vmnet11
    destroy_ssh_user = var.oltp_node_user
  }

  depends_on = [null_resource.redis_tls]

  provisioner "local-exec" {
    when        = create
    interpreter = ["pwsh", "-NoProfile", "-Command"]
    command     = <<-PWSH
      $hostName = '${each.key}'
      $ip       = '${each.value.vmnet11}'
      $sshUser  = '${var.oltp_node_user}'
      $timeout  = ${var.oltp_cluster_timeout_minutes}
      $sshOpts  = @('-o','ConnectTimeout=10','-o','BatchMode=yes','-o','StrictHostKeyChecking=no')

      $rendered = @'
${local.redis_conf_rendered[each.key]}
'@
      $rendered = $rendered -replace "`r`n","`n"
      $confB64  = [Convert]::ToBase64String([System.Text.UTF8Encoding]::new($false).GetBytes($rendered))

      Write-Host ""
      Write-Host "[redis-config $hostName] rendering redis.conf + enable/start nexus-redis.service"

      # ─── Render redis.conf + ensure data/log/run dirs + enable+start ──────
      $stage = @"
set -euo pipefail

# Directories the service needs (matches the redis.conf paths above). The
# data dir is the source of truth for nodes.conf + AOF.
sudo install -d -o redis -g redis -m 0750 /etc/nexus-redis
sudo install -d -o redis -g redis -m 0750 /var/lib/nexus-redis
sudo install -d -o redis -g redis -m 0750 /var/log/nexus-redis
# /var/run/nexus-redis -- systemd's RuntimeDirectory= owns this at runtime;
# install-time mkdir is harmless on cold boot and survives until reboot when
# RuntimeDirectory= re-creates it (per memory/feedback_systemd_runtime_
# directory_tmpfs.md). The unit file is owned by the oltp-node Packer
# template (3d), so we don't touch /etc/systemd/system/ here.
sudo install -d -o redis -g redis -m 0755 /var/run/nexus-redis

# Drop redis.conf atomically.
echo '$confB64' | base64 -d | sudo tee /etc/nexus-redis/redis.conf > /dev/null
sudo chown root:redis /etc/nexus-redis/redis.conf
sudo chmod 0640 /etc/nexus-redis/redis.conf

# Enable + restart (restart not start -- if config changed we want the new
# values picked up; on cold start restart-on-stopped is equivalent to start).
sudo systemctl daemon-reload
sudo systemctl enable nexus-redis.service
sudo systemctl restart nexus-redis.service
echo CONFIG_OK
"@
      $stageLf  = $stage -replace "`r`n", "`n"
      $stageOut = $stageLf | ssh @sshOpts "$sshUser@$ip" "tr -d '\r' | bash -s" 2>&1 | Out-String
      if ($LASTEXITCODE -ne 0 -or $stageOut -notmatch 'CONFIG_OK') {
        Write-Host $stageOut.Trim()
        throw "[redis-config $hostName] config render / service restart failed (rc=$LASTEXITCODE)"
      }

      # ─── Wait for service active + TLS PING returns PONG ──────────────────
      # Self-mTLS: the broker's own cert (client_flag=true on the redis-server
      # PKI role) doubles as its client identity for the PING.
      Write-Host "[redis-config $hostName] waiting for nexus-redis.service + TLS PING..."
      $deadline = (Get-Date).AddMinutes($timeout)
      $ok = $false
      while ((Get-Date) -lt $deadline) {
        $active = (ssh @sshOpts "$sshUser@$ip" "systemctl is-active nexus-redis.service" 2>&1 | Out-String).Trim()
        if ($active -eq 'active') {
          # PING via self-cert. sudo because TLS material is 0640 root:redis;
          # the keystore + key are NOT nexusadmin-readable.
          $ping = (ssh @sshOpts "$sshUser@$ip" "sudo redis-cli -h 127.0.0.1 -p 6379 --tls --cacert /etc/nexus-redis/tls/ca.crt --cert /etc/nexus-redis/tls/server.crt --key /etc/nexus-redis/tls/server.key PING 2>&1" | Out-String).Trim()
          if ($ping -match '^PONG$') { $ok = $true; break }
        }
        Start-Sleep -Seconds 5
      }
      if (-not $ok) {
        $journal = (ssh @sshOpts "$sshUser@$ip" "sudo journalctl -u nexus-redis.service --no-pager -n 30" 2>&1 | Out-String)
        Write-Host $journal
        throw "[redis-config $hostName] nexus-redis.service / TLS PING did not converge within $timeout min"
      }
      Write-Host "[redis-config $hostName] nexus-redis active + TLS PING -> PONG"
    PWSH
  }

  # Destroy: stop the service + remove redis.conf. nodes.conf + AOF in
  # /var/lib/nexus-redis are preserved (a `terraform destroy` of just this
  # overlay should NOT wipe cluster state). VM destroy via modules/vm
  # naturally takes the whole disk with it.
  provisioner "local-exec" {
    when        = destroy
    interpreter = ["pwsh", "-NoProfile", "-Command"]
    command     = <<-PWSH
      $hostName = '${each.key}'
      $vmIp     = '${self.triggers.destroy_vm_ip}'
      $sshUser  = '${self.triggers.destroy_ssh_user}'
      $sshOpts  = @('-o','ConnectTimeout=5','-o','BatchMode=yes','-o','StrictHostKeyChecking=no')
      Write-Host "[redis-config destroy] $${hostName}: stopping nexus-redis + removing redis.conf (preserving nodes.conf + AOF)"
      ssh @sshOpts "$sshUser@$vmIp" "sudo systemctl disable --now nexus-redis.service 2>/dev/null; sudo rm -f /etc/nexus-redis/redis.conf" 2>$null
      exit 0
    PWSH
  }
}
