/*
 * role-overlay-mongo-config.tf -- Phase 0.G.2 -- render mongod.conf + start
 *
 * Per-host /etc/nexus-mongo/mongod.conf render + nexus-mongo.service enable
 * + start + per-node TLS ping verification. Runs AFTER mongo-tls has the
 * server.pem + ca.crt + keyfile in place (depends_on chain enforces order).
 *
 * --- Config shape (mTLS-only + keyFile for RS internal auth) ---
 *
 * Network:
 *   - net.bindIp 0.0.0.0,::1          Listen on all v4 + v6 loopback
 *   - net.port 27017
 *   - net.tls.mode requireTLS         TLS-only; refuses any non-TLS connect.
 *   - net.tls.certificateKeyFile      Combined leaf + PKCS#8 key.
 *   - net.tls.CAFile                  Intermediate + root chain.
 *   - net.tls.allowConnectionsWithoutCertificates false  mTLS required.
 *
 * Replica set + auth:
 *   - replication.replSetName nexus-rs  Replica set name (rs.initiate sets
 *                                       member topology).
 *   - security.keyFile                  Shared RS internal auth secret;
 *                                       implicitly enables security.
 *                                       authorization.
 *   - security.authorization enabled   Explicit for clarity. With keyFile,
 *                                       MongoDB requires authorization on.
 *
 * Persistence + sizing:
 *   - storage.dbPath /var/lib/nexus-mongo
 *   - storage.wiredTiger.engineConfig.cacheSizeGB 0.5  CONSTRAIN cache for
 *     the lab's 2 GB nodes (mongod's default is max(50% host RAM, 256MB)
 *     which would fight other lab VMs). Sufficient for smoke + cluster
 *     bring-up workloads.
 *
 * Lifecycle:
 *   - systemLog to file (mongod.log), not journal
 *   - processManagement.fork false (systemd manages)
 *
 * --- Idempotency / verify ---
 *
 * Hash-keyed re-render. service restart on conf change (mongod has no
 * `SIGHUP` reload for most settings). TLS PING via self-cert (mongo's
 * own leaf doubles as client identity -- mongo-server role has
 * client_flag=true) returns `{ok: 1}`.
 *
 * Reachability: nftables (v2) opens 27017 on VMnet11.
 *
 * Selective ops: var.enable_mongo_config AND var.enable_mongo_tls.
 */

locals {
  mongo_config_per_host = {
    "mongo-1" = { vmnet11 = "192.168.70.71" }
    "mongo-2" = { vmnet11 = "192.168.70.72" }
    "mongo-3" = { vmnet11 = "192.168.70.73" }
  }

  mongo_config_active = {
    for host, spec in local.mongo_config_per_host : host => spec
    if(
      var.enable_mongo && var.enable_mongo_config && var.enable_mongo_tls
      && lookup(local.mongo_tls_active, host, null) != null
    )
  }

  # mongod.conf is identical across all 3 nodes (per-host identity lives in
  # rs.initiate members[]). A single rendered string keyed only by its
  # content hash + the global mongod settings.
  mongo_conf_rendered = join("\n", [
    "# Generated by nexus-infra-oltp/terraform/envs/oltp/role-overlay-mongo-config.tf",
    "# Phase 0.G.2 -- mongo replica set mTLS. Do not edit by hand.",
    "",
    "net:",
    "  bindIp: 0.0.0.0,::1",
    "  port: 27017",
    "  tls:",
    "    mode: requireTLS",
    "    certificateKeyFile: /etc/nexus-mongo/tls/server.pem",
    "    CAFile: /etc/nexus-mongo/tls/ca.crt",
    "    allowConnectionsWithoutCertificates: false",
    "    disabledProtocols: TLS1_0,TLS1_1",
    "",
    "replication:",
    "  replSetName: nexus-rs",
    "",
    "security:",
    "  keyFile: /etc/nexus-mongo/keyfile",
    "  authorization: enabled",
    "",
    "storage:",
    "  dbPath: /var/lib/nexus-mongo",
    "  wiredTiger:",
    "    engineConfig:",
    "      cacheSizeGB: 0.5",
    "",
    "systemLog:",
    "  destination: file",
    "  path: /var/log/nexus-mongo/mongod.log",
    "  logAppend: true",
    "  verbosity: 0",
    "",
    "processManagement:",
    "  fork: false",
    "  pidFilePath: /var/run/nexus-mongo/mongod.pid",
    "",
    "# (NOTE: enableLocalhostAuthBypass tried at mongo_config_v=2 + reverted.",
    "#  MongoDB 8.0 + security.keyFile + security.authorization=enabled does",
    "#  NOT activate the localhost-exception even when the setParameter is",
    "#  set. The bypass parameter loads into config but the runtime check",
    "#  still requires auth. The rs-initiate overlay now uses __system",
    "#  cluster auth via the keyFile content to bootstrap smoke-rw -- see",
    "#  role-overlay-mongo-rs-initiate.tf v5 + handbook §3.x.)",
    "",
  ])
}

resource "null_resource" "mongo_config" {
  for_each = local.mongo_config_active

  triggers = {
    tls_id         = null_resource.mongo_tls[each.key].id
    vmnet11        = each.value.vmnet11
    conf_sha       = sha256(local.mongo_conf_rendered)
    mongo_config_v = "3" # v3 (0.G.2 ratification fix 2026-05-17, second iter) = reverted v2's enableLocalhostAuthBypass setParameter. MongoDB 8.0 + security.keyFile + security.authorization=enabled does NOT activate the localhost-exception even when the bypass setParameter is set; the runtime check still requires auth. Diagnosed when createUser kept failing with "Unauthorized" despite the bypass being in the loaded config. Bootstrap now uses __system cluster auth via keyFile content (rs-initiate v5). v2 added the bypass (didn't work). v1 = initial straight-to-mTLS config.

    destroy_vm_ip    = each.value.vmnet11
    destroy_ssh_user = var.oltp_node_user
  }

  depends_on = [null_resource.mongo_tls]

  provisioner "local-exec" {
    when        = create
    interpreter = ["pwsh", "-NoProfile", "-Command"]
    command     = <<-PWSH
      $hostName = '${each.key}'
      $ip       = '${each.value.vmnet11}'
      $sshUser  = '${var.oltp_node_user}'
      $timeout  = ${var.oltp_cluster_timeout_minutes}
      $sshOpts  = @('-o','ConnectTimeout=10','-o','BatchMode=yes','-o','StrictHostKeyChecking=no')

      $rendered = @'
${local.mongo_conf_rendered}
'@
      $rendered = $rendered -replace "`r`n","`n"
      $confB64  = [Convert]::ToBase64String([System.Text.UTF8Encoding]::new($false).GetBytes($rendered))

      Write-Host ""
      Write-Host "[mongo-config $hostName] rendering mongod.conf + enable/start nexus-mongo.service"

      $stage = @"
set -euo pipefail

# Directories the mongod process needs (matches mongod.conf paths).
sudo install -d -o mongodb -g mongodb -m 0750 /etc/nexus-mongo
sudo install -d -o mongodb -g mongodb -m 0750 /var/lib/nexus-mongo
sudo install -d -o mongodb -g mongodb -m 0750 /var/log/nexus-mongo
# /var/run/nexus-mongo: systemd RuntimeDirectory= owns this at runtime,
# but an install-time mkdir is harmless on cold boot.
sudo install -d -o mongodb -g mongodb -m 0755 /var/run/nexus-mongo

# Drop mongod.conf atomically.
echo '$confB64' | base64 -d | sudo tee /etc/nexus-mongo/mongod.conf > /dev/null
sudo chown root:mongodb /etc/nexus-mongo/mongod.conf
sudo chmod 0640 /etc/nexus-mongo/mongod.conf

sudo systemctl daemon-reload
sudo systemctl enable nexus-mongo.service
sudo systemctl restart nexus-mongo.service
echo CONFIG_OK
"@
      $stageLf  = $stage -replace "`r`n", "`n"
      $stageOut = $stageLf | ssh @sshOpts "$sshUser@$ip" "tr -d '\r' | bash -s" 2>&1 | Out-String
      if ($LASTEXITCODE -ne 0 -or $stageOut -notmatch 'CONFIG_OK') {
        Write-Host $stageOut.Trim()
        throw "[mongo-config $hostName] config render / service restart failed (rc=$LASTEXITCODE)"
      }

      # ─── Wait for service active + TLS ping returns ok:1 ──────────────────
      # Self-mTLS via the node's own cert. mongosh needs sudo to read the
      # 0640 root:mongodb server.pem. Use mongosh --quiet to suppress the
      # interactive banner so the eval output is parseable.
      Write-Host "[mongo-config $hostName] waiting for nexus-mongo.service + TLS ping..."
      $deadline = (Get-Date).AddMinutes($timeout)
      $ok = $false
      while ((Get-Date) -lt $deadline) {
        $active = (ssh @sshOpts "$sshUser@$ip" "systemctl is-active nexus-mongo.service" 2>&1 | Out-String).Trim()
        if ($active -eq 'active') {
          # ping via self-mTLS. --quiet suppresses the banner; the eval
          # prints `{ ok: 1 }` on success. Use --apiVersion 1 to lock the
          # CLI to the stable API surface.
          $ping = (ssh @sshOpts "$sshUser@$ip" "sudo mongosh --quiet --tls --tlsCAFile /etc/nexus-mongo/tls/ca.crt --tlsCertificateKeyFile /etc/nexus-mongo/tls/server.pem --host 127.0.0.1:27017 --eval 'db.adminCommand({ping: 1}).ok' 2>&1" | Out-String).Trim()
          if ($ping -match '^1$') { $ok = $true; break }
        }
        Start-Sleep -Seconds 5
      }
      if (-not $ok) {
        $journal = (ssh @sshOpts "$sshUser@$ip" "sudo journalctl -u nexus-mongo.service --no-pager -n 30; sudo tail -50 /var/log/nexus-mongo/mongod.log 2>/dev/null" 2>&1 | Out-String)
        Write-Host $journal
        throw "[mongo-config $hostName] nexus-mongo.service / TLS ping did not converge within $timeout min"
      }
      Write-Host "[mongo-config $hostName] nexus-mongo active + TLS ping -> ok:1"
    PWSH
  }

  # Destroy: stop service + remove mongod.conf. /var/lib/nexus-mongo is
  # preserved (RS member identity + data live there).
  provisioner "local-exec" {
    when        = destroy
    interpreter = ["pwsh", "-NoProfile", "-Command"]
    command     = <<-PWSH
      $hostName = '${each.key}'
      $vmIp     = '${self.triggers.destroy_vm_ip}'
      $sshUser  = '${self.triggers.destroy_ssh_user}'
      $sshOpts  = @('-o','ConnectTimeout=5','-o','BatchMode=yes','-o','StrictHostKeyChecking=no')
      Write-Host "[mongo-config destroy] $${hostName}: stopping nexus-mongo + removing mongod.conf (preserving /var/lib/nexus-mongo)"
      ssh @sshOpts "$sshUser@$vmIp" "sudo systemctl disable --now nexus-mongo.service 2>/dev/null; sudo rm -f /etc/nexus-mongo/mongod.conf" 2>$null
      exit 0
    PWSH
  }
}
